import { ComboBox, Slider } from "std-widgets.slint";
import { StereoVisual } from "stereo-visual.slint";
import { Theme } from "theme.slint";
import { AudioState } from "audio-state.slint";


export component Channel {
    in property <string> name;
    in property <float> initialVolume: 1;

    VerticalLayout {
        Text {
            text: name;
            color: Theme.secondary;
            font-size: 0.9rem;
            height: 1.2rem;
        }

        HorizontalLayout {
            ComboBox {
                model: AudioState.source_names;
                max-height: 2rem;
            }
        }

        HorizontalLayout {
            alignment: center;
            padding-top: 0.5rem;
            padding-bottom: 0.5rem;

            stereo := StereoVisual {
                leftVolume: slider.value;
                rightVolume: slider.value;
            }

            Rectangle {
                width: 0.7rem;
            }

            slider := Slider {
                orientation: vertical;
                minimum: 0;
                maximum: 1;
                value: initialVolume;

                changed(value) => {
                    stereo.leftVolume = value;
                    stereo.rightVolume = value;
                }
            }
        }

        HorizontalLayout {
            ComboBox {
                model: AudioState.sink_names;
                max-height: 2rem;
            }
        }
    }
}
