export global Theme {
    in-out property <color> primary: #fbf1c7;
    in-out property <color> secondary: #ebdbb2;
    in-out property <color> tertiary: #d5c4a1;
    in-out property <color> quaternary: #bdae93;
    in-out property <color> background0: #32302f;
    in-out property <color> background1: #3c3836;
    in-out property <color> background2: #504945;
    in-out property <color> background3: #665c54;
    in-out property <color> lighter_pink: #eed1d8;
    in-out property <color> light_pink: #e1abb9;
    in-out property <color> pink: #d3869b;
    in-out property <color> dark_pink: #c5607b;
    in-out property <color> darker_pink: #b2415f;
    in-out property <color> lighter_red: #db9696;
    in-out property <color> light_red: #ce7070;
    in-out property <color> red: #c14a4a;
    in-out property <color> dark_red: #a13737;
    in-out property <color> darker_red: #7b2a2a;
    in-out property <color> lighter_orange: #f3ccb2;
    in-out property <color> light_orange: #ecaf86;
    in-out property <color> orange: #e5915a;
    in-out property <color> dark_orange: #de742e;
    in-out property <color> darker_orange: #bb5d1d;
    in-out property <color> lighter_yellow: #ebd2aa;
    in-out property <color> light_yellow: #e2bc80;
    in-out property <color> yellow: #d8a657;
    in-out property <color> dark_yellow: #cc902f;
    in-out property <color> darker_yellow: #a37326;
    in-out property <color> lighter_green: #acdabc;
    in-out property <color> light_green: #89caa0;
    in-out property <color> green: #66ba83;
    in-out property <color> dark_green: #4aa369;
    in-out property <color> darker_green: #3a8053;
    in-out property <color> lighter_cyan: #bed0c9;
    in-out property <color> light_cyan: #a0bab0;
    in-out property <color> cyan: #83a598;
    in-out property <color> dark_cyan: #678e7f;
    in-out property <color> darker_cyan: #517064;
    in-out property <color> lighter_blue: #8ab5ce;
    in-out property <color> light_blue: #669fbf;
    in-out property <color> blue: #4786ab;
    in-out property <color> dark_blue: #386a87;
    in-out property <color> darker_blue: #294e63;
    in-out property <color> lighter_purple: #d3a6ba;
    in-out property <color> light_purple: #c284a0;
    in-out property <color> purple: #b16286;
    in-out property <color> dark_purple: #964a6c;
    in-out property <color> darker_purple: #733954;
    // aliases
    in-out property <color> active: #ebdbb2; // secondary
    in-out property <color> inactive: #3c3836; // background1
    in-out property <color> error: #c14a4a; // red
    in-out property <color> warning: #d8a657; // yellow
    in-out property <color> success: #66ba83; // green
    in-out property <color> info: #83a598; // cyan
    in-out property <color> working: #83a598; // cyan
    in-out property <color> important: #e5915a; // orange
}
